workflows:
  default:
    name: Default Workflow
    environment:
      flutter: 3.22.2
      java: 17
    scripts:
      - name: Remove default deps step and fix project
        script: |
          flutter clean
          rm -rf android ios web linux macos windows
          flutter create .
          flutter pub upgrade --major-versions
          cd android
          ./gradlew wrapper --gradle-version=8.4 --distribution-type=all
          cd ..
      - name: Build debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build//outputs//*.apk
