workflows:
  android-workflow:
    name: Android Workflow
    environment:
      flutter: 3.22.0
      java: 17
    scripts:
      - name: Fix everything
        script: |
          flutter clean
          rm -rf android ios linux macos web windows
          flutter create .
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' android/app/build.gradle
          sed -i 's/compileSdkVersion flutter.compileSdkVersion/compileSdkVersion 34/g' android/app/build.gradle
          sed -i 's/targetSdkVersion flutter.targetSdkVersion/targetSdkVersion 34/g' android/app/build.gradle
          flutter pub get
      - name: Build APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
